### ISSUE TITLE
Here's a fun one: Wrong Date

### ISSUE THREAD

**Issue by stekza01** [RoomReserve/RoomReserve#122]
When we get the date of today we're apparently not getting the date of our current timezone but actually the timezone of the server that we are on. We can get the current time of a specific timezone by passing in the timezone we want into .now() but .today() does not seem to have this feature.

**Comment by ryanpoints** [comment]
Ugh

**Comment by dhondo01** [comment]
Where is the wrong date? Is it in reservations.py? I will find a solution.

**Comment by ryanpoints** [comment]
It's not really in any of the python files we've written, it's that `datetime.now()` gets the current time from the server. This is not an issue on our localhost macs because the time on our computers is correct for our timezone. 

Heroku, however, uses a different timezone, probably `UTC+0`. We may need to find some way to convert that into a user-defined timezone.

**Comment by dhondo01** [comment]
I see, that's interesting. There must be way.

**Comment by dhondo01** [comment]
I guess datetime.now() is different when running locally and on heroku server.

**Comment by ryanpoints** [comment]
I know the `Delorean` package (installed already) has some way of converting timezones

**Comment by dhondo01** [comment]
That's good to know.
